version: "3"
services:
  rest-number:
    image: "quarkus/rest-number-api-jvm"
    ports:
      - "8701:8701"
  rest-book:
    image: "quarkus/rest-book-api-jvm"
    ports:
      - "8702:8702"
    environment:
      - NUMBER_PROXY_MP_REST_URL=http://rest-number:8701