apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"todo-web-application-h2"},"name":"todo-web-application-h2","namespace":"default"},"spec":{"minReadySeconds":45,"replicas":2,"selector":{"matchLabels":{"app":"todo-web-application-h2"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"todo-web-application-h2"}},"spec":{"containers":[{"image":"seydanurdemir/todo-web-application-h2:0.0.1-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"todo-web-application-h2"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2022-12-28T21:27:09Z"
  generation: 1
  labels:
    app: todo-web-application-h2
  name: todo-web-application-h2
  namespace: default
  resourceVersion: "2491833"
  uid: 2e78347f-4153-45a7-9176-f425e148f88b
spec:
  minReadySeconds: 45
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-web-application-h2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-web-application-h2
    spec:
      containers:
      - image: seydanurdemir/todo-web-application-h2:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: todo-web-application-h2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-12-28T21:28:02Z"
    lastUpdateTime: "2022-12-28T21:28:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-12-28T21:27:09Z"
    lastUpdateTime: "2022-12-28T21:28:02Z"
    message: ReplicaSet "todo-web-application-h2-667f6c8cd9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
