apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"todo-web-application-h2"},"name":"todo-web-application-h2","namespace":"default"},"spec":{"ports":[{"nodePort":32259,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"todo-web-application-h2"},"sessionAffinity":"ClientIP","type":"LoadBalancer"}}
  creationTimestamp: "2022-12-28T21:27:09Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: todo-web-application-h2
  name: todo-web-application-h2
  namespace: default
  resourceVersion: "2491711"
  uid: 9e794a45-50bb-4012-969f-803d582d9c81
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.4.13.142
  clusterIPs:
  - 10.4.13.142
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32259
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-application-h2
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.70.158.39
